import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args){
        Scanner scanner = new Scanner(System.in);
//        while(scanner.hasNext()){
//            System.out.println(new GuessNumberGame().process(scanner.nextLine()));
//        }
    }
}
